prep-html-links - Derren Pamintuan
derrenpamintuan/lfz-prep-0123-code-solutions pull request #4
Opened 2023-01-11 01:33 UTC by derrenpamintuan

https://user-images.githubusercontent.com/121917503/211697046-fd1a0d9a-953f-4c25-9f46-c65e56aa0139.mp4

2023-01-11 02:21 UTC, BrettAlbright requested changes
just a couple small updates are needed!

2023-01-11 02:21 UTC, BrettAlbright commented on prep-html-links/contact-us/contact-us.html
> +  <a href="http://localhost:5500/prep-html-links/index.html">Click here to go to the home page</a>
you want to avoid localhost here, you just want the relative path to the index.html file

2023-01-11 02:21 UTC, BrettAlbright commented on prep-html-links/index.html
> +  <a href="http://localhost:5500/prep-html-links/contact-us/contact-us.html">Click here to go to the contact page</a>
same as above, you want to avoid localhost here, you just want the relative path to the prep-html-links/index.html file

2023-01-12 02:40 UTC, derrenpamintuan commented
https://user-images.githubusercontent.com/121917503/211962941-91d52c15-94b9-4c8f-80eb-7566d5964127.mp4

2023-01-13 19:42 UTC, Zhiwutian approved these changes
👍🏼

2023-01-13 23:53 UTC, merged